"""initial schema

Revision ID: a74672cdac5f
Revises: 
Create Date: 2026-08-09 10:48:37.758773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74672cdac5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_uid', sa.String(length=32), nullable=False),
    sa.Column('best_known_full_name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.String(length=16), nullable=True),
    sa.Column('review_status', sa.Enum('auto_accepted', 'needs_review', 'human_reviewed', name='reviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_uid')
    )
    op.create_table('review_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.Enum('ingestion', 'extraction', 'resolution', 'qa_audit', 'full_pipeline', name='runtype'), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', 'budget_stopped', name='runstatus'), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('total_documents', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_tokens_in', sa.Integer(), nullable=False),
    sa.Column('total_tokens_out', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relpath', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('declared_extension', sa.String(length=16), nullable=False),
    sa.Column('sniffed_type', sa.Enum('pdf_digital', 'pdf_scanned', 'docx', 'xlsx', 'csv', 'eml', 'html', 'png', 'txt', 'unknown', name='doctype'), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'parsed', 'quarantined', 'failed', name='documentstatus'), nullable=False),
    sa.Column('quarantine_reason', sa.String(length=255), nullable=True),
    sa.Column('parent_document_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parsed_text_chars', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relpath')
    )
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_index('ix_documents_sha256_dedup', 'documents', ['sha256'], unique=False)
    op.create_table('exposure_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('ssn', 'dob', 'drivers_license', 'passport', 'financial_account', 'card_number', 'medical', 'login_credentials', 'home_address', 'phone', 'email', 'full_name', name='piicategory'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.Enum('auto_accepted', 'needs_review', 'human_reviewed', name='reviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'category', name='uq_person_category')
    )
    op.create_index(op.f('ix_exposure_flags_person_id'), 'exposure_flags', ['person_id'], unique=False)
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('step_type', sa.String(length=64), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_run_id'), 'steps', ['run_id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('ssn', 'dob', 'drivers_license', 'passport', 'financial_account', 'card_number', 'medical', 'login_credentials', 'home_address', 'phone', 'email', 'full_name', name='piicategory'), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('passage', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('deterministic_regex', 'deterministic_checksum', 'llm_cheap', 'llm_strong', name='extractionmethod'), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('suppressed_as_false_positive', sa.Boolean(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extractions_category', 'extractions', ['category'], unique=False)
    op.create_index(op.f('ix_extractions_document_id'), 'extractions', ['document_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('arguments_json', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_step_id'), 'tool_calls', ['step_id'], unique=False)
    op.create_table('entity_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.Enum('deterministic_exact', 'deterministic_fuzzy', 'agent_adjudicated', name='entitylinkmethod'), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extraction_id')
    )
    op.create_index(op.f('ix_entity_links_person_id'), 'entity_links', ['person_id'], unique=False)
    op.create_table('flag_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exposure_flag_id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exposure_flag_id'], ['exposure_flags.id'], ),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flag_evidence_exposure_flag_id'), 'flag_evidence', ['exposure_flag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flag_evidence_exposure_flag_id'), table_name='flag_evidence')
    op.drop_table('flag_evidence')
    op.drop_index(op.f('ix_entity_links_person_id'), table_name='entity_links')
    op.drop_table('entity_links')
    op.drop_index(op.f('ix_tool_calls_step_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_extractions_document_id'), table_name='extractions')
    op.drop_index('ix_extractions_category', table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_steps_run_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_exposure_flags_person_id'), table_name='exposure_flags')
    op.drop_table('exposure_flags')
    op.drop_index('ix_documents_sha256_dedup', table_name='documents')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('runs')
    op.drop_table('review_decisions')
    op.drop_table('persons')
    # ### end Alembic commands ###
