"""add record_key to extractions

Revision ID: f183d5dec75f
Revises: a74672cdac5f
Create Date: 2026-08-09 10:58:26.883901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f183d5dec75f'
down_revision: Union[str, Sequence[str], None] = 'a74672cdac5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractions', sa.Column('record_key', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extractions', 'record_key')
    # ### end Alembic commands ###
